// Central icon shim — re-exports Phosphor Icons under the names the codebase
// already uses (previously from lucide-react). Swapping the icon library only
// requires changing import paths to '@/components/icons'; all JSX stays the same.
// The global duotone weight is applied via <IconProvider> (see icon-provider.tsx).
export {
  WarningCircle as AlertCircle,
  Robot as Bot,
  Check,
  Check as CheckIcon,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUpIcon,
  Circle,
  Code as Code2,
  Command,
  Copy,
  DownloadSimple as Download,
  PencilSimple as Edit2,
  File,
  FileText,
  Globe,
  Image,
  Keyboard,
  CircleNotch as Loader2,
  ArrowsOut as Maximize2,
  List as Menu,
  ChatCircle as MessageSquare,
  Moon,
  Pencil,
  Plus,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Sparkle as Sparkles,
  Star,
  StopCircle,
  Sun,
  Trash as Trash2,
  UploadSimple as Upload,
  User,
  X,
  X as XIcon,
} from '@phosphor-icons/react'
